CREATE SEQUENCE SEQ_EMPLOYEE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEPARTMENT START WITH 1 INCREMENT BY 1;

CREATE TABLE EMPLOYEE (
    ID INTEGER DEFAULT (NEXT VALUE FOR SEQ_EMPLOYEE) NOT NULL,
    NAMEFIRST VARCHAR(255),
    NAMELAST VARCHAR(255),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID)
);

CREATE TABLE DEPARTMENT (
    ID INTEGER DEFAULT (NEXT VALUE FOR SEQ_DEPARTMENT) NOT NULL,
    NAME VARCHAR(255) UNIQUE,
    READONLY BOOLEAN,
    MANDATORY BOOLEAN,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID)
);

CREATE TABLE MAP_EMPLOYEE_DEPARTMENT (
    ID_DEPARTMENT INTEGER,
    ID_EMPLOYEE INTEGER,
    PRIMARY KEY (ID_EMPLOYEE, ID_DEPARTMENT),
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT(ID) ON DELETE CASCADE
);
